"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MENU_BUTTON_CLS = exports.TOOLBAR_BUTTON_CLS = exports.TOOLBAR_ICON_BUTTON_CLS = exports.BASE_TOOLBAR_BUTTON_CLS = exports.SECONDARY_BUTTON_CLS = exports.PRIMARY_BUTTON_CLS = exports.BASE_PRIMARY_BUTTON_CLS = exports.PILL_BUTTON_CLS = exports.BUTTON_PADDING = exports.ROUNDED_BUTTON_CLS = exports.CENTERED_BUTTON_CLS = exports.FOCUS_BORDER_CLS = exports.FOCUS_RING_CLS = exports.COL_BUTTON_CLS = exports.ROW_BUTTON_CLS = exports.BASE_BUTTON_CLS = exports.PRIMARY_LINK_CLS = exports.PRIMARY_TEXT_CLS = exports.PRIMARY_BUTTON_W_CLS = exports.BUTTON_W_CLS = exports.BUTTON_H_CLS = exports.PRIMARY_FOCUS_BORDER_CLS = exports.PRIMARY_FOCUS_RING_CLS = exports.PRIMARY_BUTTON_BG_CLS = exports.DROPDOWN_BG_CLS = exports.INPUT_DARK_CLS = exports.BASE_INPUT_DARK_CLS = exports.INPUT_DARK_BG_CLS = exports.INPUT_BG_CLS = exports.INPUT_DARK_BORDER_CLS = exports.INPUT_BORDER_CLS = exports.ROUNDED_CLS = void 0;
var class_names_1 = __importDefault(require("@lib/class-names"));
exports.ROUNDED_CLS = "rounded-md";
exports.INPUT_BORDER_CLS = "border-gray-200/90";
exports.INPUT_DARK_BORDER_CLS = "dark:border-gray-700/80";
exports.INPUT_BG_CLS = "bg-gray-100";
exports.INPUT_DARK_BG_CLS = "dark:bg-gray-700";
exports.BASE_INPUT_DARK_CLS = (0, class_names_1.default)("trans-300 transition-colors", exports.INPUT_BG_CLS, exports.INPUT_DARK_BG_CLS, "dark:hover:bg-gray-600");
exports.INPUT_DARK_CLS = (0, class_names_1.default)(exports.INPUT_BORDER_CLS, exports.BASE_INPUT_DARK_CLS, exports.INPUT_DARK_BORDER_CLS);
exports.DROPDOWN_BG_CLS = "bg-white dark:bg-gray-700";
exports.PRIMARY_BUTTON_BG_CLS = "bg-primary-500 hover:bg-primary-600";
exports.PRIMARY_FOCUS_RING_CLS = "focus-visible:ring-primary-300/80 dark:focus-visible:ring-gray-200";
exports.PRIMARY_FOCUS_BORDER_CLS = "focus-visible:border-primary-300/80 dark:focus-visible:border-gray-200";
exports.BUTTON_H_CLS = "min-h-9";
exports.BUTTON_W_CLS = "min-w-9";
exports.PRIMARY_BUTTON_W_CLS = "min-w-24";
exports.PRIMARY_TEXT_CLS = "text-primary-500 dark:text-gray-100";
exports.PRIMARY_LINK_CLS = (0, class_names_1.default)(exports.PRIMARY_TEXT_CLS, "hover:text-primary-600");
exports.BASE_BUTTON_CLS = "trans-300 transition-all group";
exports.ROW_BUTTON_CLS = "flex flex-row items-center";
exports.COL_BUTTON_CLS = "flex flex-col";
exports.FOCUS_RING_CLS = "outline-none focus-visible:ring-2";
exports.FOCUS_BORDER_CLS = "outline-none border-2 border-transparent";
exports.CENTERED_BUTTON_CLS = "flex flex-row items-center justify-center";
exports.ROUNDED_BUTTON_CLS = exports.ROUNDED_CLS;
exports.BUTTON_PADDING = "gap-x-2 px-3";
exports.PILL_BUTTON_CLS = "rounded-full overflow-hidden";
exports.BASE_PRIMARY_BUTTON_CLS = (0, class_names_1.default)(exports.BUTTON_H_CLS, exports.ROW_BUTTON_CLS, exports.ROUNDED_BUTTON_CLS, exports.PRIMARY_BUTTON_W_CLS, exports.CENTERED_BUTTON_CLS);
exports.PRIMARY_BUTTON_CLS = (0, class_names_1.default)(exports.BUTTON_PADDING, exports.BASE_PRIMARY_BUTTON_CLS, exports.PRIMARY_BUTTON_BG_CLS, "font-semibold text-white");
exports.SECONDARY_BUTTON_CLS = (0, class_names_1.default)(exports.BASE_PRIMARY_BUTTON_CLS, exports.PRIMARY_FOCUS_RING_CLS, "font-semibold", "bg-gray-200 hover:bg-gray-300 dark:bg-gray-600 dark:hover:bg-gray-500");
exports.BASE_TOOLBAR_BUTTON_CLS = (0, class_names_1.default)(exports.BASE_BUTTON_CLS, exports.BUTTON_H_CLS, exports.ROW_BUTTON_CLS, exports.PRIMARY_FOCUS_RING_CLS, "hover:bg-gray-200/70 dark:hover:bg-gray-600");
exports.TOOLBAR_ICON_BUTTON_CLS = (0, class_names_1.default)(exports.BASE_TOOLBAR_BUTTON_CLS, exports.BUTTON_W_CLS, exports.ROUNDED_BUTTON_CLS, "justify-center");
exports.TOOLBAR_BUTTON_CLS = (0, class_names_1.default)(exports.BASE_TOOLBAR_BUTTON_CLS, exports.BUTTON_PADDING, exports.ROUNDED_BUTTON_CLS, "justify-center");
exports.MENU_BUTTON_CLS = (0, class_names_1.default)(exports.BASE_TOOLBAR_BUTTON_CLS, exports.ROUNDED_BUTTON_CLS, exports.BUTTON_PADDING, "w-full text-left whitespace-nowrap");
//# sourceMappingURL=theme.js.map