export declare const LOGIN_ROUTE = "/login";
export declare const ORDER_ITEM_TEXT = "Order Item";
export declare const ORDER_BUTTON_TEXT = "Order";
export declare const DELETE_TEXT = "Delete";
export declare const NO_RESULTS_TEXT = "Nothing to see here.";
export declare const ALT_TEXT_CLS = "text-gray-400 dark:text-gray-500";
export declare const CENTER_CONTENT_CLS = "flex flex-col h-screen pt-8 md:pt-16 items-center gap-y-8";
export declare const BASE_FORM_CLS = "flex flex-col gap-y-4 text-sm";
export declare const FORM_CLS: any;
export declare const FORM_DIV_CLS: any;
export declare const FORM_BLOCK_CLS = "flex flex-col gap-y-2";
export declare const INPUT_LABEL_CLS = "text-xs font-semibold text-gray-400 dark:text-gray-500 tracking-wide";
export declare const INPUT_CLS: any;
export declare const TABLE_CLS = "text-sm";
export declare const TD_CLS = "p-2 align-top";
export declare const TH_CLS: any;
export declare const FILTER_BUTTON_CLS = "px-2 py-1.5 text-theme-500 border border-theme-300 rounded-full";
export declare const ALT_TR_CLS = "bg-gray-100";
export declare const TBODY_CLS = "border border-gray-200 bg-white text-sm";
export declare const SIDE_DROPDOWN_CLS: any;
export declare const CHEVRON_CLS = "stroke-gray-600 dark:stroke-white";
export declare const STATUS_CODE_OK = 200;
export declare const STATUS_SUCCESS = "success";
export declare const STATUS_FAIL = "fail";
export declare const COLOR_THEME = "color-theme";
