export declare const ROUNDED_CLS = "rounded-md";
export declare const INPUT_BORDER_CLS = "border-gray-200/90";
export declare const INPUT_DARK_BORDER_CLS = "dark:border-gray-700/80";
export declare const INPUT_BG_CLS = "bg-gray-100";
export declare const INPUT_DARK_BG_CLS = "dark:bg-gray-800";
export declare const BASE_INPUT_DARK_CLS: any;
export declare const INPUT_DARK_CLS: any;
export declare const PRIMARY_BUTTON_BG_CLS = "bg-theme-500 hover:bg-theme-600";
export declare const PRIMARY_FOCUS_BORDER_CLS = "focus-visible:border-theme-300/80 dark:focus-visible:border-gray-200";
export declare const BUTTON_H_CLS = "min-h-9";
export declare const BUTTON_W_CLS = "min-w-9";
export declare const ICON_BUTTON_SIZE_CLS: any;
export declare const PRIMARY_BUTTON_W_CLS = "min-w-24";
export declare const DEFAULT_BUTTON_SIZE_CLS: any;
export declare const PRIMARY_TEXT_CLS = "text-primary";
export declare const PRIMARY_LINK_CLS: any;
export declare const ROW_BUTTON_CLS = "inline-flex flex-row items-center";
export declare const COL_BUTTON_CLS = "flex flex-col";
export declare const FOCUS_RING_CLS = "focus-visible:ring-2 focus-visible:ring-ring";
export declare const GROUP_FOCUS_RING_CLS = "group-focus-visible:ring-2 group-focus-visible:ring-ring";
export declare const FOCUS_BORDER_CLS = "outline-none border-2 border-transparent";
export declare const CENTERED_BUTTON_CLS = "flex flex-row items-center justify-center";
export declare const ROUNDED_BUTTON_CLS = "rounded-md";
export declare const BUTTON_PADDING = "gap-x-2 px-3";
export declare const PILL_BUTTON_CLS = "rounded-full overflow-hidden";
export declare const BASE_BUTTON_CLS: any;
export declare const ICON_BUTTON_CLS: any;
export declare const BASE_PRIMARY_BUTTON_CLS: any;
export declare const PRIMARY_BUTTON_CLS: any;
export declare const SECONDARY_BUTTON_CLS: any;
export declare const BASE_TOOLBAR_BUTTON_CLS: any;
export declare const TOOLBAR_ICON_BUTTON_CLS: any;
export declare const TOOLBAR_BUTTON_CLS: any;
export declare const MENU_BUTTON_CLS: any;
